---
- name: Install and Start the service
  hosts: localhost
  become: true
  gather_facts: no

  tasks:
  - name: Installing nginx
    apt:
      name: nginx
      state: present
      update_cache: yes

  - name: Starting the nginx service
    service:
      name: nginx
      state: started
      enabled: true